# Generated by Django 3.0.2 on 2022-12-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='CatNom',
            field=models.CharField(max_length=50, verbose_name='Nombre de la categoría'),
        ),
    ]
