# Generated by Django 3.0.2 on 2022-12-24 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20221224_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='CatImg',
            field=models.ImageField(blank=True, null=True, upload_to='pics/categorias', verbose_name='Imagen'),
        ),
    ]
