# Generated by Django 3.0.2 on 2022-12-26 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_categoria_catimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='CatImg',
            field=models.ImageField(null=True, upload_to='media/pics/categorias'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='CatNom',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
    ]
