# Generated by Django 3.0.2 on 2022-12-24 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0003_categoria_catimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productName', models.CharField(max_length=32)),
                ('productDescription', models.CharField(max_length=64)),
                ('productPrice', models.FloatField()),
                ('productCategory', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.Categoria')),
            ],
        ),
    ]
