# Generated by Django 3.0.2 on 2022-12-24 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='productImage',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
