# Generated by Django 3.0.2 on 2022-12-25 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_categoria_catimg'),
        ('productos', '0002_producto_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='productCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='categorias.Categoria'),
        ),
    ]
