# Generated by Django 3.0.2 on 2022-12-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razonsocial', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=300)),
                ('telefono', models.IntegerField()),
                ('representante', models.CharField(max_length=300)),
                ('fechacontratacion', models.DateField()),
            ],
        ),
    ]
